# -*- coding: utf-8 -*-
# Copyright 2017-2019 ControlScan, Inc.
#
# This file is part of Cyphon Engine.
#
# Cyphon Engine is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# Cyphon Engine is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Cyphon Engine. If not, see <http://www.gnu.org/licenses/>.
#
# Generated by Django 1.10.1 on 2017-03-20 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('containers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taste',
            fields=[
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('location_format', models.CharField(blank=True, choices=[('LNG/LAT', 'Longitude, Latitude'), ('LAT/LNG', 'Latitude, Logitude')], default='LNG/LAT', max_length=10, null=True)),
                ('datetime', models.CharField(blank=True, max_length=255, null=True)),
                ('date_string', models.CharField(blank=True, help_text='An alternative to a datetime field. Use if the date is a string rather than a DateTime object.', max_length=255, null=True)),
                ('date_format', models.CharField(blank=True, help_text='If a date string is used, please enter its date format, if known (e.g., %Y-%m-%d %H:%M:%S %z).', max_length=255, null=True)),
                ('container', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='containers.Container')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
