from django.contrib import admin
from dfirtrack_main.models import Analysisstatus, Analystmemo, Case, Company, Contact, Division, Dnsname, Domain, Domainuser, Entry, Headline, Ip, Location, Os, Osarch, Osimportname, Reason, Recommendation, Reportitem, Serviceprovider, System, Systemstatus, Systemtype, Systemuser, Tag, Task, Taskname

# all registered models will show up in admin app
admin.site.register(Analysisstatus)
admin.site.register(Analystmemo)
admin.site.register(Case)
admin.site.register(Company)
admin.site.register(Contact)
admin.site.register(Division)
admin.site.register(Dnsname)
admin.site.register(Domain)
admin.site.register(Domainuser)
admin.site.register(Entry)
admin.site.register(Headline)
admin.site.register(Ip)
admin.site.register(Location)
admin.site.register(Os)
admin.site.register(Osarch)
admin.site.register(Osimportname)
admin.site.register(Reason)
admin.site.register(Recommendation)
admin.site.register(Reportitem)
admin.site.register(Serviceprovider)
admin.site.register(System)
admin.site.register(Systemstatus)
admin.site.register(Systemtype)
admin.site.register(Systemuser)
admin.site.register(Tag)
admin.site.register(Task)
admin.site.register(Taskname)
