# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_remove_muzzle_hash_null'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='last_modified',
            new_name='last_updated',
        ),
    ]
