# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_auto_20170717_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='created_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
