# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0010_remove_alert_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='distillery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alerts', related_query_name='alerts', to='distilleries.Distillery'),
        ),
    ]
