# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0013_transfer_alert_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='notes',
        ),
    ]
