# Generated by Django 2.0.2 on 2018-03-20 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dfirtrack_main', '0001_initial'),
    ]

    operations = [

        migrations.RunSQL("INSERT INTO dfirtrack_main_analysisstatus (analysisstatus_name) VALUES ('10_needs_analysis');"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_analysisstatus (analysisstatus_name) VALUES ('20_ready_for_analysis');"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_analysisstatus (analysisstatus_name) VALUES ('30_ongoing_analysis');"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_analysisstatus (analysisstatus_name) VALUES ('40_nothing_to_do');"),

        migrations.RunSQL("INSERT INTO dfirtrack_main_headline (headline_name) VALUES ('Summary');"),

        migrations.RunSQL("INSERT INTO dfirtrack_main_os (os_name) VALUES ('Windows Server 2003');"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_os (os_name) VALUES ('Windows Server 2003 R2');"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_os (os_name) VALUES ('Windows Server 2008');"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_os (os_name) VALUES ('Windows Server 2008 R2');"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_os (os_name) VALUES ('Windows Server 2012');"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_os (os_name) VALUES ('Windows Server 2012 R2');"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_os (os_name) VALUES ('Windows Server 2016');"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_os (os_name) VALUES ('Windows XP');"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_os (os_name) VALUES ('Windows Vista');"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_os (os_name) VALUES ('Windows 7');"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_os (os_name) VALUES ('Windows 8');"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_os (os_name) VALUES ('Windows 8.1');"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_os (os_name) VALUES ('Windows 10');"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_os (os_name) VALUES ('tbd');"),

        migrations.RunSQL("INSERT INTO dfirtrack_main_osarch (osarch_name) VALUES ('32-Bit');"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_osarch (osarch_name) VALUES ('64-Bit');"),

        migrations.RunSQL("INSERT INTO dfirtrack_main_systemstatus (systemstatus_name) VALUES ('10_unknown');"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_systemstatus (systemstatus_name) VALUES ('20_analysis_ongoing');"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_systemstatus (systemstatus_name) VALUES ('30_compromised');"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_systemstatus (systemstatus_name) VALUES ('40_clean');"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_systemstatus (systemstatus_name) VALUES ('50_remediation_done');"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_systemstatus (systemstatus_name) VALUES ('60_reinstalled');"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_systemstatus (systemstatus_name) VALUES ('70_removed');"),

        migrations.RunSQL("INSERT INTO dfirtrack_main_systemtype (systemtype_name) VALUES ('Domaincontroller');"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_systemtype (systemtype_name) VALUES ('Mailserver');"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_systemtype (systemtype_name) VALUES ('Fileserver');"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_systemtype (systemtype_name) VALUES ('USB-Drive');"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_systemtype (systemtype_name) VALUES ('Client');"),

        migrations.RunSQL("INSERT INTO dfirtrack_main_tagcolor (tagcolor_name) VALUES ('primary');"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_tagcolor (tagcolor_name) VALUES ('green');"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_tagcolor (tagcolor_name) VALUES ('orange');"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_tagcolor (tagcolor_name) VALUES ('red');"),

        migrations.RunSQL("INSERT INTO dfirtrack_main_taskpriority (taskpriority_name) VALUES ('10_low');"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_taskpriority (taskpriority_name) VALUES ('20_medium');"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_taskpriority (taskpriority_name) VALUES ('30_high');"),

        migrations.RunSQL("INSERT INTO dfirtrack_main_taskstatus (taskstatus_name) VALUES ('10_pending');"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_taskstatus (taskstatus_name) VALUES ('20_working');"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_taskstatus (taskstatus_name) VALUES ('30_done');"),

    ]
