# Generated by Django 2.0.2 on 2018-03-20 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dfirtrack_main', '0002_default_values'),
    ]

    operations = [

        migrations.RunSQL("INSERT INTO dfirtrack_main_tag (tag_name, tagcolor_id) VALUES ('Suspicious', (SELECT tagcolor_id FROM dfirtrack_main_tagcolor WHERE tagcolor_name='orange'));"),

        migrations.RunSQL("INSERT INTO dfirtrack_main_tag (tag_name, tagcolor_id) VALUES ('Backdoor installed', (SELECT tagcolor_id FROM dfirtrack_main_tagcolor WHERE tagcolor_name='red'));"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_tag (tag_name, tagcolor_id) VALUES ('Credential harvesting', (SELECT tagcolor_id FROM dfirtrack_main_tagcolor WHERE tagcolor_name='red'));"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_tag (tag_name, tagcolor_id) VALUES ('Data theft', (SELECT tagcolor_id FROM dfirtrack_main_tagcolor WHERE tagcolor_name='red'));"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_tag (tag_name, tagcolor_id) VALUES ('Important', (SELECT tagcolor_id FROM dfirtrack_main_tagcolor WHERE tagcolor_name='red'));"),

    ]
