# Generated by Django 2.0 on 2018-09-27 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dfirtrack_main', '0004_changed_fqdn_to_dnssuffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_modified_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tag_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
