# Generated by Django 2.0.2 on 2018-11-15 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dfirtrack_main', '0005_added_tag_note_and_user'),
    ]

    operations = [

        migrations.RunSQL("INSERT INTO dfirtrack_main_tagcolor (tagcolor_name) VALUES ('black');"),
        migrations.RunSQL("INSERT INTO dfirtrack_main_tagcolor (tagcolor_name) VALUES ('white');"),

    ]
