# Generated by Django 2.0.2 on 2019-01-21 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dfirtrack_main', '0006_tagcolors'),
    ]

    operations = [

        migrations.RunSQL("INSERT INTO dfirtrack_main_systemstatus (systemstatus_name) VALUES ('90_not_analyzed');"),

        migrations.RunSQL("INSERT INTO dfirtrack_main_analysisstatus (analysisstatus_name) VALUES ('50_main_analysis_finished');"),

    ]
