# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['title']},
        ),
    ]
