# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasieves', '0002_auto_20170602_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarule',
            name='operator',
            field=models.CharField(choices=[('CharField:x', 'contains'), ('CharField:^x', 'begins with'), ('CharField:x$', 'ends with'), ('CharField:^x$', 'equals'), ('FloatField:>', 'greater than'), ('FloatField:>=', 'greater than or equal to'), ('FloatField:<', 'less than'), ('FloatField:<=', 'less than or equal to'), ('EmptyField', 'is null')], help_text='The type of comparison to make.', max_length=40),
        ),
    ]
